name: Push workflow
on: [push]
jobs:
  build-docker-images:
    name: Build Docker images
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: GHCR Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker Buildx builder setup
        uses: docker/setup-buildx-action@v3.6.1
      -
        name: Docker Bake
        uses: docker/bake-action@v5.7.0
        with:
          source: https://github.com/rcwbr/dockerfile-partials.git#main
          files: github-cache-bake.hcl
        env:
          REGISTRY: ghcr.io/rcwbr/
          IMAGE_NAME: release-it-docker
