name: Push workflow
on: push
jobs:
  # All PR jobs should be listed in required_status_checks https://github.com/rcwbr/release-it-docker/blob/0e9a5bcd8da40cac01686b6312df09bffdee810e/.github/settings.yml#L54
  build-docker-images:
    name: Build Docker images
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: GHCR Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker Buildx builder setup
        uses: docker/setup-buildx-action@v3.6.1
      -
        name: Docker Bake base
        uses: docker/bake-action@v5.7.0
        with:
          workdir: base
          source: https://github.com/rcwbr/dockerfile-partials.git#main
          files: github-cache-bake.hcl
          set: |
            default.context=cwd://
        env:
          REGISTRY: ghcr.io/rcwbr/
          IMAGE_NAME: release-it-docker
      -
        name: Docker Bake conventional-changelog
        uses: docker/bake-action@v5.7.0
        with:
          workdir: conventional-changelog
          source: https://github.com/rcwbr/dockerfile-partials.git#main
          files: github-cache-bake.hcl, cwd://docker-bake.hcl
          set: |
            default.context=cwd://
        env:
          REGISTRY: ghcr.io/rcwbr/
          IMAGE_NAME: release-it-docker-conventional-changelog
  release-it-dry-run:
    name: Release-it dry-run
    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      -
        name: Release-it
        uses: rcwbr/release-it-action/conventional-changelog-action@1-define-initial-action
        with:
          release-it-extra-args: --changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-it:
    name: Release-it
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    # Run full release process for pushes to main
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      -
        name: Release-it
        uses: rcwbr/release-it-action/conventional-changelog-action@1-define-initial-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
