name: Push workflow
on: push
jobs:
  # All PR jobs should be listed in required_status_checks https://github.com/rcwbr/release-it-docker/blob/0e9a5bcd8da40cac01686b6312df09bffdee810e/.github/settings.yml#L54
  build-docker-images:
    name: Build Docker images
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: GHCR Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker Buildx builder setup
        uses: docker/setup-buildx-action@v3.6.1
      -
        id: docker-bake-base
        name: Docker Bake base
        uses: docker/bake-action@v5.7.0
        with:
          workdir: base
          source: https://github.com/rcwbr/dockerfile-partials.git#0.1.0
          files: github-cache-bake.hcl
          set: |
            default.context=cwd://
        env:
          REGISTRY: ghcr.io/rcwbr/
          IMAGE_NAME: release-it-docker
      -
        id: docker-bake-conventional-changelog
        name: Docker Bake conventional-changelog
        uses: docker/bake-action@v5.7.0
        with:
          workdir: conventional-changelog
          source: https://github.com/rcwbr/dockerfile-partials.git#0.1.0
          files: github-cache-bake.hcl, cwd://docker-bake.hcl
          set: |
            default.context=cwd://
        env:
          REGISTRY: ghcr.io/rcwbr/
          IMAGE_NAME: release-it-docker-conventional-changelog
      -
        id: docker-bake-file-bumper
        name: Docker Bake file-bumper
        uses: docker/bake-action@v5.7.0
        with:
          workdir: file-bumper
          source: https://github.com/rcwbr/dockerfile-partials.git#0.1.0
          files: github-cache-bake.hcl, cwd://docker-bake.hcl
          set: |
            default.context=cwd://
        env:
          REGISTRY: ghcr.io/rcwbr/
          IMAGE_NAME: release-it-docker-file-bumper
    outputs:
      docker-bake-base-metadata: ${{ steps.docker-bake-base.outputs.metadata }}
      docker-bake-conventional-changelog-metadata: ${{ steps.docker-bake-conventional-changelog.outputs.metadata }}
      docker-bake-file-bumper-metadata: ${{ steps.docker-bake-file-bumper.outputs.metadata }}
  release-it-workflow:
    uses: rcwbr/release-it-gh-workflow/.github/workflows/release-it-workflow.yaml@0.1.0
    needs: build-docker-images
    with:
      release-it-config: /.tag-only-release-it.json
      release-it-image: ${{ fromJSON(needs.build-docker-images.outputs.docker-bake-file-bumper-metadata)['default']['image.name'] }}
      app-id: 1033419 # release-it-docker CI release-it app
      app-environment: Repo release
    secrets:
      app-secret: ${{ secrets.RELEASE_IT_GITHUB_APP_KEY }} # Secret belonging to the Repo release environment
